# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "build"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: "checkout sources"
        uses: actions/checkout@v4

      - name: "install dependencies"
        run: npm install

      - name: "run eslint"
        run: npm run lint

      - name: "run mocha tests (with coverage)"
        run: npm run test-with-coverage

      - name: "build"
        run: npm run build

      - name: "build src"
        run: npm run build-src

      - name: "build docs"
        run: npm run jsdoc

#      - name: "send code coverage report to codecov.io"
#        uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: .build/coverage-js/clover.xml

#      - name: "publish docs to gh-pages"
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages
#          folder: .build/jsdoc
#          clean: true

      - name: "upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: example-${{ github.sha }}
          path: ./dist
